<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use App\Models\User;

class UsersSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('users')->insert([
            [
                'name' => 'Ahmed Salah',
                'email' => 'ahmed@example.com',
                'password' => Hash::make('password123'),
                'role' => 'student',
                'profile_picture' => 'profile1.jpg',
                'bio' => 'AI developer and machine learning enthusiast.',
                'linkedin' => 'https://linkedin.com/in/ahmedsalah',
                'github' => 'https://github.com/ahmedsalah',
                'is_verified' => true,
                'national_id' => '11111111111111',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Sara Mohamed',
                'email' => 'sara@example.com',
                'password' => Hash::make('password123'),
                'role' => 'graduate',
                'profile_picture' => 'profile2.jpg',
                'bio' => 'React developer who loves building UIs.',
                'linkedin' => 'https://linkedin.com/in/saramohamed',
                'github' => 'https://github.com/saramohamed',
                'is_verified' => true,
                'national_id' => '22222222222222',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Ali Hassan',
                'email' => 'ali@example.com',
                'password' => Hash::make('password123'),
                'role' => 'mentor',
                'profile_picture' => 'profile3.jpg',
                'bio' => 'Cybersecurity specialist and penetration tester.',
                'linkedin' => 'https://linkedin.com/in/alihassan',
                'github' => 'https://github.com/alihassan',
                'is_verified' => true,
                'national_id' => '33333333333333',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Mona Tarek',
                'email' => 'mona@example.com',
                'password' => Hash::make('password123'),
                'role' => 'admin',
                'profile_picture' => 'profile4.jpg',
                'bio' => 'System admin managing the platform.',
                'linkedin' => 'https://linkedin.com/in/monatarek',
                'github' => 'https://github.com/monatarek',
                'is_verified' => true,
                'national_id' => '44444444444444',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // --- 10 extra users with unique data ---
            [
                'name' => 'Lara Jensen',
                'email' => 'lara.jensen@example.com',
                'password' => Hash::make('password123'),
                'role' => 'student',
                'profile_picture' => 'profile5.jpg',
                'bio' => 'Frontend developer passionate about Angular.',
                'linkedin' => 'https://linkedin.com/in/larajensen',
                'github' => 'https://github.com/larajensen',
                'is_verified' => true,
                'national_id' => '55555555555555',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'John Smith',
                'email' => 'john.smith@example.com',
                'password' => Hash::make('password123'),
                'role' => 'graduate',
                'profile_picture' => 'profile6.jpg',
                'bio' => 'Backend developer and API architect.',
                'linkedin' => 'https://linkedin.com/in/johnsmith',
                'github' => 'https://github.com/johnsmith',
                'is_verified' => true,
                'national_id' => '66666666666666',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Emily Davis',
                'email' => 'emily.davis@example.com',
                'password' => Hash::make('password123'),
                'role' => 'student',
                'profile_picture' => 'profile7.jpg',
                'bio' => 'Passionate about mobile development with Flutter.',
                'linkedin' => 'https://linkedin.com/in/emilydavis',
                'github' => 'https://github.com/emilydavis',
                'is_verified' => true,
                'national_id' => '77777777777777',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Mark Lee',
                'email' => 'mark.lee@example.com',
                'password' => Hash::make('password123'),
                'role' => 'mentor',
                'profile_picture' => 'profile8.jpg',
                'bio' => 'DevOps engineer and cloud consultant.',
                'linkedin' => 'https://linkedin.com/in/marklee',
                'github' => 'https://github.com/marklee',
                'is_verified' => true,
                'national_id' => '88888888888888',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Sophia Brown',
                'email' => 'sophia.brown@example.com',
                'password' => Hash::make('password123'),
                'role' => 'graduate',
                'profile_picture' => 'profile9.jpg',
                'bio' => 'Tech writer and documentation specialist.',
                'linkedin' => 'https://linkedin.com/in/sophiabrown',
                'github' => 'https://github.com/sophiabrown',
                'is_verified' => true,
                'national_id' => '99999999999999',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Tom Wilson',
                'email' => 'tom.wilson@example.com',
                'password' => Hash::make('password123'),
                'role' => 'student',
                'profile_picture' => 'profile10.jpg',
                'bio' => 'Loves JavaScript and Node.js.',
                'linkedin' => 'https://linkedin.com/in/tomwilson',
                'github' => 'https://github.com/tomwilson',
                'is_verified' => true,
                'national_id' => '10101010101010',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Nora Black',
                'email' => 'nora.black@example.com',
                'password' => Hash::make('password123'),
                'role' => 'graduate',
                'profile_picture' => 'profile11.jpg',
                'bio' => 'QA engineer and test automation expert.',
                'linkedin' => 'https://linkedin.com/in/norablack',
                'github' => 'https://github.com/norablack',
                'is_verified' => true,
                'national_id' => '12121212121212',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Jake Adams',
                'email' => 'jake.adams@example.com',
                'password' => Hash::make('password123'),
                'role' => 'mentor',
                'profile_picture' => 'profile12.jpg',
                'bio' => 'Tech lead with 10+ years in startups.',
                'linkedin' => 'https://linkedin.com/in/jakeadams',
                'github' => 'https://github.com/jakeadams',
                'is_verified' => true,
                'national_id' => '13131313131313',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Olivia White',
                'email' => 'olivia.white@example.com',
                'password' => Hash::make('password123'),
                'role' => 'admin',
                'profile_picture' => 'profile13.jpg',
                'bio' => 'Platform coordinator and support lead.',
                'linkedin' => 'https://linkedin.com/in/oliviawhite',
                'github' => 'https://github.com/oliviawhite',
                'is_verified' => true,
                'national_id' => '14141414141414',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
